[package]
name = "pixelguard"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
image = "0.25.6"
opener = "0.8.2"
oxipng = "9.1.5"
rfd = "0.15.3"
tokio = "1.45.1"
webp = "0.3.0"
